"""
SQLAlchemy declarative base and shared mixins.

All ORM models must inherit from Base.
Shared concerns (timestamps, soft-delete, UUID PKs) live here.
"""

import json
import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import ARRAY, Text, TypeDecorator


def utcnow() -> datetime:
    """Always-aware UTC datetime."""
    return datetime.now(tz=timezone.utc)


class StringArray(TypeDecorator):
    """
    Cross-dialect array type that uses native PostgreSQL ARRAY(Text)
    in production and JSON-serialized TEXT in SQLite for testing.
    """
    impl = ARRAY(Text)
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "sqlite":
            return dialect.type_descriptor(Text())
        return dialect.type_descriptor(ARRAY(Text()))

    def process_bind_param(self, value, dialect):
        if dialect.name == "sqlite":
            return json.dumps(value) if value is not None else None
        return value

    def process_result_value(self, value, dialect):
        if dialect.name == "sqlite" and isinstance(value, str):
            try:
                return json.loads(value)
            except Exception:
                return [value]
        return value


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""
    pass


class UUIDPrimaryKeyMixin:
    """Mixin that provides a UUID v4 primary key generated by PostgreSQL."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Mixin that provides created_at and updated_at timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        server_default=text("NOW()"),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utcnow,
        onupdate=utcnow,
        server_default=text("NOW()"),
        nullable=False,
    )


class SoftDeleteMixin:
    """
    Mixin for soft deletion.
    Records are never physically deleted — deleted_at is set instead.
    All queries against soft-deletable models MUST filter WHERE deleted_at IS NULL.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None

    def soft_delete(self) -> None:
        self.deleted_at = utcnow()
